# Configurações de Build
[build]
  publish = "client"
  command = "npm install"
  functions = "netlify/functions"

# Redirecionamentos da API
[[redirects]]
  from = "/api/exchange-rate"
  to = "/.netlify/functions/exchange-rate"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/historical/*"
  to = "/.netlify/functions/historical-rate/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirecionamento SPA (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração do ambiente
[build.environment]
  NODE_VERSION = "18"

# Headers globais
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers específicos para arquivos estáticos
[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
    [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configurações das funções Netlify
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]