# Configurações de Build
[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  publish = "."
  port = 3000
  targetPort = 3000
  framework = "#static"

# Redirecionamentos da API
[[redirects]]
  from = "/api/exchange-rate"
  to = "/.netlify/functions/exchange-rate"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"

[[redirects]]
  from = "/api/historical/*"
  to = "/.netlify/functions/historical-rate/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"