[build]
  publish = "client"
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
    [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"